# Generated by Django 5.1.5 on 2025-03-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('keywords', models.CharField(blank=True, max_length=256)),
                ('url_image', models.FileField(upload_to='activities/%Y/%m')),
                ('status_student', models.CharField(choices=[('1', 'PSD'), ('2', 'PCD'), ('3', 'Não Definido')], max_length=20)),
                ('licence', models.BooleanField(default=False, help_text='Você confirma que a imagem enviada esta livre de direitos autorais e/ou autoriza o uso dela?')),
                ('slug', models.SlugField(blank=True, max_length=64)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('user_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(help_text='Nome da aula', max_length=30, verbose_name='Matéria')),
                ('day_week', models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-Feira'), ('2', 'Terça-Feira'), ('3', 'Quarta-Feira'), ('4', 'Quinta-Feira'), ('5', 'Sexta-Feira'), ('6', 'Sábado')], max_length=20)),
                ('hour', models.TimeField(help_text='Horario de início da aula', verbose_name='Inicio Aula')),
                ('duration', models.IntegerField(default=50, help_text='Duração da aula (em minutos)', verbose_name='Duração da aula')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('school', models.ForeignKey(default='Escola Sem Nome', on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.school', verbose_name='Escola')),
            ],
        ),
    ]
