# Generated by Django 5.1.5 on 2025-03-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activities',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
    ]
