# Generated by Django 5.1.4 on 2024-12-30 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(help_text='Nome da aula', max_length=30, verbose_name='Matéria')),
                ('hour', models.TimeField(help_text='Horario de início da aula', verbose_name='Inicio Aula')),
                ('duration', models.FloatField(default=50, help_text='Duração da aula (em minutos)', verbose_name='Duração da aula')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.school', verbose_name='Escola')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
