# Generated by Django 5.1.4 on 2024-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_matter_delete_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='images/logo_schools/'),
        ),
    ]
