# Generated by Django 5.1.4 on 2024-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_school_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='day_week',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-Feira'), ('2', 'Terça-Feira'), ('3', 'Quarta-Feira'), ('4', 'Quinta-Feira'), ('5', 'Sexta-Feira'), ('6', 'Sábado')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
