# Generated by Django 5.1.4 on 2024-12-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_matter_day_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='duration',
            field=models.IntegerField(default=50, help_text='Duração da aula (em minutos)', verbose_name='Duração da aula'),
        ),
    ]
