# Generated by Django 5.1.4 on 2025-01-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_matter_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo_image',
        ),
        migrations.AlterField(
            model_name='matter',
            name='school',
            field=models.ForeignKey(default='Escola Sem Nome', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.school', verbose_name='Escola'),
        ),
    ]
