# Generated by Django 5.1.4 on 2025-02-07 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('keywords', models.CharField(blank=True, max_length=256)),
                ('url_image', models.FileField(upload_to='activities/%Y/%m')),
                ('status_student', models.CharField(choices=[('1', 'Normal'), ('2', 'Especial')], max_length=20)),
                ('licence', models.BooleanField(default=False, help_text='Você confirma que a imagem enviada esta livre de direitos autorais e/ou autoriza o uso dela?')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('user_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
