# Generated by Django 5.1.4 on 2025-02-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
