# Generated by Django 5.1.5 on 2025-02-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_activities_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='status_student',
            field=models.CharField(choices=[('1', 'PSD'), ('2', 'PCD')], max_length=20),
        ),
    ]
