# Generated by Django 5.1.4 on 2025-02-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
