# Generated by Django 5.1.5 on 2025-02-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='slug',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='activities',
            name='status_student',
            field=models.CharField(choices=[('1', 'PSD'), ('2', 'PCD'), ('3', 'Não Definido')], max_length=20),
        ),
    ]
