# Generated by Django 5.1.4 on 2025-02-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_activities_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status_student',
            field=models.CharField(choices=[('1', 'PSD'), ('2', 'PCD'), ('3', 'Não Definido')], max_length=20),
        ),
    ]
