# Generated by Django 5.1.4 on 2025-02-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_activities_slug_alter_activities_status_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
