# Generated by Django 5.1.6 on 2025-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_promptia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptia',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
