# Generated by Django 5.1.6 on 2025-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_promptia_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptia',
            options={'verbose_name': 'Prompt Ia', 'verbose_name_plural': 'Prompts Ia'},
        ),
        migrations.RemoveField(
            model_name='promptia',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='promptia',
            name='Atualizado em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
