# Generated by Django 5.1.5 on 2025-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_promptia_options_remove_promptia_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptia',
            name='inference_counts',
            field=models.IntegerField(default=0),
        ),
    ]
