# Generated by Django 5.1.5 on 2025-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_promptia_inference_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptia',
            name='Atualizado em',
        ),
        migrations.AddField(
            model_name='promptia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
