# Generated by Django 5.1.5 on 2025-03-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_promptia_atualizado_em_promptia_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptIa',
        ),
    ]
