# Generated by Django 5.1.5 on 2025-03-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_promptia'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='school',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schools',
            field=models.ManyToManyField(to='teachers.school'),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Matter',
        ),
    ]
